<?xml version = "1.0" standalone="yes"?>
<!DOCTYPE student[
    <!ELEMENT student (name,address,email,phoneno.)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT phoneno. (#PCDATA)>
]>
<student>
    <name>Sohan Shrestha</name>
    <address>Nepal</address>
    <email>xyz12@gmail.com</email>
    <phoneno.>9876543210</phoneno.>
</student>